version: '3'

services:
  frontend:
    image: local/frontend
    build:
      context: .
      dockerfile: Frontend.Dockerfile
  ingredients:
    image: local/ingredients
    build:
      context: .
      dockerfile: Ingredients.Dockerfile
  orders:
    image: local/orders
    build:
      context: .
      dockerfile: Orders.Dockerfile